In [3]:
import autograd.numpy as np
import autograd

In [14]:
def f1(a, b):
    return np.dot(a, b)

In [6]:
f1_d = autograd.grad(f1)

In [10]:
a = np.arange(10).astype(float)
b = 10 - a

In [11]:
f1(a, b)

165.0

In [12]:
f1_d(a, b)

array([ 10.,   9.,   8.,   7.,   6.,   5.,   4.,   3.,   2.,   1.])

In [19]:
def f2(a):
    return np.linalg.det(a)

In [24]:
m1 = np.array([[1,2],[3, 4]])

In [25]:
f2(m1)

-2.0000000000000004

In [26]:
f2_d = autograd.grad(f2)

In [27]:
f2_d(m1)

array([[ 4., -3.],
       [-2.,  1.]])

In [28]:
def f3(a):
    return np.linalg.slogdet(a)[1]

In [29]:
f3_d = autograd.grad(f3)

In [31]:
f3_d(m1)

array([[-2. ,  1.5],
       [ 1. , -0.5]])