In [1]:
import numpy as np
from maxvolpy.maxvol import maxvol
from numpy.polynomial import Chebyshev as T
import numpy.linalg as la
import matplotlib.pyplot as plt
from scipy.linalg import lu as lu
from gen_1D import *
from ids import *
%matplotlib inline

In [2]:
### how to make from permatation matrix readable array
def perm_array(A):
    p_a = np.array((A.shape[0]))
    p_a = np.argmax(A, axis = 1)
    return p_a

In [3]:
n = 4 #nmber of sampling points   
deg = 3 # Degree of polynomiapaired plu Last Checkpoint: 22 minutes ago (unsaved changes)l          
interval = [-3, 3]  # interval of x
x = np.linspace(interval[0], interval[1], n, dtype=np.float64)
p_size = deg+1

In [4]:
### generating matrix with special structure
b = Gen_1D_coupled(p_size, x, debug=True)
b

number of points(l) = 4,  number of monoms(n_size) = 4


array([[   1.,   -3.,   17.,  -99.],
       [   0.,    1.,  -12.,  105.],
       [   1.,   -1.,    1.,   -1.],
       [   0.,    1.,   -4.,    9.],
       [   1.,    1.,    1.,    1.],
       [   0.,    1.,    4.,    9.],
       [   1.,    3.,   17.,   99.],
       [   0.,    1.,   12.,  105.]])

In [5]:
p,l,u,q = pluq_ids(b)

[[   1.    0.]
 [  -3.    1.]
 [  17.  -12.]
 [ -99.  105.]]
[[ 1.  0.]
 [-1.  1.]
 [ 1. -4.]
 [-1.  9.]]
[[ 1.  0.]
 [ 1.  1.]
 [ 1.  4.]
 [ 1.  9.]]
[[   1.    0.]
 [   3.    1.]
 [  17.   12.]
 [  99.  105.]]
correct 2x2 matrix
('on the', 0, 'slice')
('best row block is', 0, 1)
('column coordinates:', 2, 3)
('maxvol 2x2 submatrix', array([[  17.,  -12.],
       [ -99.,  105.]]))
('with det = ', 596.99999999999955)
pivoting and permutations start...
[[ 0.84422111  0.52261307]
 [-0.67001675 -0.16080402]]
[[ 0.8040201  -0.88442211]
 [ 1.39363484  2.73366834]]
[[ -3.9798995   -4.22110553]
 [ 12.30150754   8.68341709]]
correct 2x2 matrix
('on the', 2, 'slice')
('best row block is', 6, 7)
('column coordinates:', 2, 3)
('maxvol 2x2 submatrix', array([[ -3.9798995 ,  -4.22110553],
       [ 12.30150754,   8.68341709]]))
('with det = ', 17.366834170854279)
pivoting and permutations start...


In [6]:
### here we can see that in the first 4 rows blocked structure was saved, i.e. func-deriv, func-deriv
perm_array(p)

array([0, 1, 6, 7, 4, 5, 2, 3])

In [7]:
### maxvol preprocessing
ids = np.dot(p,np.dot(b,q))[:p_size]
A = np.dot(p,np.dot(b,q))

temp = np.dot(A,np.linalg.inv(ids))

In [ ]:
### here we are checking all pairs under Identity matrix and try to find 2x2 block with det>1+tol
tol = 0.05
n = temp.shape[0]
m = temp.shape[1]
for k in range(m,n,2):
        pair = np.concatenate((temp[k,:],temp[k+1,:])).reshape(2,m).T
        piv,_ = maxvol(pair)
        piv = np.sort(piv)
        print pair, pair[piv]
        if (np.abs(np.linalg.det(pair[piv])) > (1 + tol)):
            print('exist!')